targets:
  $default:
    builders:
      drift_dev:
        options:
          # Generate modular, readable code and use the recommended defaults.
          store_date_time_values_as_text: true
          named_parameters: true
